### model
# llamafactory-cli export merge_lora_config.yaml

model_name_or_path: ../model_ckpt/Meta-Llama-3.1-8B-Instruct
adapter_name_or_path: ../saves/Llama-3.1-8B-Instruct/CellHermes
template: llama3
finetuning_type: lora

### export
export_dir: ../model_ckpt/CellHermes
export_size: 2
export_device: cpu
export_legacy_format: false